
////
This file is generated! See fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by Com.Redhat.Viaq. They are
grouped in the following categories:

* <<exported-fields-_default_>>
* <<exported-fields-openstack>>

[[exported-fields-_default_]]
=== Common logging metadata Fields

Contains common fields, this is what populates the actual the mappings of the _default_. Oritinated from the mapping for rsyslog clients, but can be used with other clients as well. _type of the documents should be 'rsyslog'



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ||yyyy-MM-dd'T'HH:mm:ssZ||dateOptionalTime

UTC value marking when the log payload was created, or when log payload was first collected if the creation time is not known;  this is the log processing pipeline’s “best effort” determination of when the log payload was generated FYI: the “@” prefix convention to note a field as being reserved for a particular use; in this case, most tools by default look for “@timestamp” with ElasticSearch


==== CEE

type: object

Previously a CEE structure as it comes from rsyslog. TODO: come up with a good name as CEE is very specific to syslog


==== geoip

type: object

geo-ip of the machine


==== hostname

type: string

FQDN of the entity generating the original payload This field is a best effort attempt to derive this context; sometimes the entity generating it knows it; other times that entity has a restricted namespace itself, and the collector or normalizer knows that


==== ipaddr4

type: ip

IP address v4 of the source server, can be an array.


==== ipaddr6

type: string

IP address v6 of the source server(if available).


==== level

type: string

example: info

Loging level as provided by: rsyslog(severitytext property), python's logging module, etc. Possible values: info, warning, notice, err, debug


==== message

type: string

example: TODO

Typical log entry message, or payload, possibly stripped of metadata pulled out of it by collector/normalizer, UTF-8 encoded.


==== pid

type: string

PID... look into details on systemd stuff


==== service

type: string

name of the service. syslog's APP-NAME and programname are renamed to service field as well.


==== tags

type: string

Field contains whitespace-delimited tags. Tagging is configured on normalizers/collectors. Please note that this field is analyzed and not an array since rsyslog doesn't play well with JSON lists


==== file

type: string

Full local path. TODO: analyzer for file paths


==== offset

type: long

Offset in the log file.


=== pipeline_metadata Fields

Metadata related to ViaQ log collection pipeline. Everything about log collector, normalizers goes here. Data in this subgroup is stored for troublehsooting purposes mostly.



=== collector Fields

The section contains metadata specific to the collector.



==== hostname

type: string

FQDN of the collector. It might be different from the FQDN of the actual emitter of the logs.


==== ipaddr4

type: ip

IP address v4 of the collector server, can be an array.


==== inputname

type: string

how the log message was received on the collector whether it was TCP/UDP, or maybe imjournal/imfile.


==== received_at

type: date

format: yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ||yyyy-MM-dd'T'HH:mm:ssZ||dateOptionalTime

Time when the message was received at the collector.


=== normalizer Fields

The section contains metadata specific to the normalizer.



==== hostname

type: string

FQDN of the normalizer.


==== ipaddr4

type: ip

IP address v4 of the normalizer server, can be an array.


==== inputname

type: string

how the log message was received on the normalizer whether it was TCP/UDP.


==== received_at

type: date

format: yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ||yyyy-MM-dd'T'HH:mm:ssZ||dateOptionalTime

Time when the message was received at the collector.


==== @version

type: string

example: TODO

Version of “com.redhat.viaq” mapping the document is intended to adhere by the normalizer. It must be set by the normalizer.  The value must correspond to the [_meta][version].


==== original_raw_message

type: string

The original non-parsed log message, collected by collector or as close to the source as possible.


==== trace

type: string

example: rsyslog,8.16,2016.02.01 logstash,1.5,2016.03.03

The field records the trace of the message. Each collector/normalizer appends information about itself and the date/time when the message was processed.


=== rsyslog Fields

rsyslog/syslog-specific metadata, excluding systemd metadata.



==== facility

type: string

rsyslog's facility. see syslog specification for more information


==== protocol-version

type: string

rsyslog protocol version


==== structured-data

type: string

syslog's structured-data. see syslog specification for more information


=== systemd Fields

systemd-specific metadata.



=== k Fields

systemd's kernel-specific metadata.



==== KERNEL_DEVICE

type: string

TODO


==== KERNEL_SUBSYSTEM

type: string

TODO


==== UDEV_DEVLINK

type: string

TODO


==== UDEV_DEVNODE

type: string

TODO


==== UDEV_SYSNAME

type: string

TODO


=== t Fields

TODO.



==== AUDIT_LOGINUID

type: string

TODO


==== BOOT_ID

type: string

TODO


==== AUDIT_SESSION

type: string

TODO


==== CAP_EFFECTIVE

type: string

TODO


==== CMDLINE

type: string

TODO


==== COMM

type: string

TODO


==== EXE

type: string

TODO


==== GID

type: string

TODO


==== HOSTNAME

type: string

TODO


==== MACHINE_ID

type: string

TODO


==== PID

type: string

TODO


==== SELINUX_CONTEXT

type: string

TODO


==== SOURCE_REALTIME_TIMESTAMP

type: string

TODO


==== SYSTEMD_CGROUP

type: string

TODO


==== SYSTEMD_OWNER_UID

type: string

TODO


==== SYSTEMD_SESSION

type: string

TODO


==== SYSTEMD_SLICE

type: string

TODO


==== SYSTEMD_UNIT

type: string

TODO


==== SYSTEMD_USER_UNIT

type: string

TODO


==== TRANSPORT

type: string

TODO


==== UID

type: string

TODO


=== u Fields

TODO.



==== CODE_FILE

type: string

TODO


==== CODE_FUNCTION

type: string

TODO


==== CODE_LINE

type: string

TODO


==== ERRNO

type: string

TODO


==== MESSAGE_ID

type: string

TODO


==== RESULT

type: string

TODO


==== UNIT

type: string

TODO


[[exported-fields-openstack]]
=== OpenStack-specific information Fields

Mapping specifically for openstack. Inherits all the fields from __default__ _type of the documents in this mapping should be openstack



[[exported-fields-openstack]]
=== OpenStack-specific information Fields

TODO.



==== instance

type: string

TODO.


==== context

type: string

We understand this to be a value scraped from the originating HTTP REST API request so that one can track related API requests throughout the stack, as such it is an identifier and should not be tokenized when indexed.


==== class

type: string

TODO.


